name: "CloudStrap.bg документация : app --help"
timezone: Europe/Sofia
permalink: /blog/:title.html

header_title: "> app --help | more"
header_lead: "Бърз поглед на <strong>CloudStrap</strong>, как да създаваме и управляваме нашите приложения."

keywords: ""
description: ""

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

pygments: true

asset_pipeline:
  bundle: false            # Default = true
  compress: false          # Default = true
  output_path: assets     # Default = assets
  display_path: nil       # Default = nil
  gzip: false             # Default = false

#Table of content default label
contentsLabel: "Съдържание"

cloudstrap:
  groups: "https://groups.google.com/d/forum/cloudstrapio"
  support_email: "support@cloudstrap.io"
  github: "https://github.com/startapp-cloud"
  github_docs: "https://github.com/startapp-cloud/docs"
  github_docs_new_issue: "https://github.com/startapp-cloud/docs/issues/new"
  tools_page : "/getting-started/app-client-tools-install.html"
  irc: "http://webchat.freenode.net/?randomnick=1&channels=startapp"
  new_account: "http://www.cloudstrap.io/"
